"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowUpRight, Badge, Check, Clock3, Crown, Droplets, Footprints, Hand, Mail, MapPin, Menu, MessageCircle, Palette, Phone, ScanFace, Scissors, Sparkles, Star, Waves, X } from "lucide-react";
import { salon, services, packages, testimonials, serviceMessage, whatsappUrl } from "../lib/salon-data";

const icons={Scissors,Sparkles,Badge,Palette,Waves,ScanFace,Droplets,Hand,Footprints,Crown};
const nav=["About","Services","Packages","Pricing","Gallery","Reviews","Contact"];
const general=()=>`Hello The Hair Club, I would like to book an appointment at your Ali Town salon. Please share the available dates and timings. Thank you.`;

function Brand(){return <a href="#home" className="brand" aria-label="The Hair Club home"><Image src="/images/the-hair-club-logo.png" width={180} height={104} alt="The Hair Club — Signature by Ayyan Azhar" className="brand-logo" priority/></a>}
function Navbar(){const[open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);return <header className="site-header"><div className="shell nav-shell"><Brand light/><nav className="desktop-nav" aria-label="Main navigation">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><a href="#book" className="button-gold desktop-book">Book appointment</a><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-menu"><nav>{nav.map((x,i)=><a key={x} onClick={()=>setOpen(false)} href={`#${x.toLowerCase()}`}><span>{String(i+1).padStart(2,"0")}</span>{x}</a>)}</nav><a onClick={()=>setOpen(false)} href="#book" className="button-gold">Book appointment</a></div>}</header>}
function SectionTitle({kicker,title,text,dark=false}){return <div className={`section-heading reveal ${dark?"text-white":""}`}><p className="eyebrow">{kicker}</p><h2>{title}</h2>{text&&<p className="section-copy">{text}</p>}</div>}
function Hero(){return <section id="home" className="hero"><Image src="/images/hero-men.png" alt="Professional barber finishing a client's haircut in a luxury men's salon" fill priority sizes="100vw" className="hero-image"/><div className="hero-shade"/><div className="shell hero-content"><div><p className="eyebrow">Modern grooming, mastered.</p><h1>Look sharp.<br/><em>Feel certain.</em></h1><p className="hero-copy">Precision cuts, considered grooming and uncompromising care—crafted for men who value the details.</p><div className="hero-actions"><a href="#book" className="button-gold">Book appointment</a><a href={whatsappUrl(general())} target="_blank" rel="noreferrer" className="button-ghost"><MessageCircle size={18}/> Book on WhatsApp</a></div></div><span className="open-now"><Clock3 size={17}/> Open today · 10 AM — 9 PM</span></div></section>}
function About(){return <section id="about" className="section about"><div className="shell split"><div className="about-image"><Image src="/images/grooming-editorial.png" alt="Modern men's haircut, beard styling and facial treatment" fill sizes="(max-width:1024px) 100vw,52vw" className="cover left"/><span>Signature grooming<br/>by Ayyan Azhar</span></div><div><SectionTitle kicker="The Hair Club standard" title={<>More than a cut.<br/><em>A ritual.</em></>} text="THE HAIR CLUB is a contemporary men’s salon built around expertise, consistency and the kind of service you look forward to."/><div className="check-grid">{["Experienced professionals","Premium products","Immaculate hygiene","Personal consultation"].map(x=><div key={x}><Check size={17}/>{x}</div>)}</div></div></div></section>}
function Services(){return <section id="services" className="section services"><div className="shell"><SectionTitle dark kicker="Our expertise" title={<>Grooming, <em>refined.</em></>} text="Every service starts with a consultation and ends with a finish tailored to you."/><div className="service-grid">{services.map((s,i)=>{const Icon=icons[s.icon];return <article className="service-card reveal" style={{"--delay":`${(i%3)*80}ms`}} key={s.name}><div className="service-top"><span>{String(i+1).padStart(2,"0")}</span><span className="service-icon"><Icon/></span></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-bottom"><span className="service-price"><small>Starting from</small><b>{s.price}</b></span><a className="service-book" href={whatsappUrl(serviceMessage(s.name))} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Book on WhatsApp <ArrowUpRight size={16}/></a></div></article>})}</div></div></section>}
function Packages(){return <section id="packages" className="section packages"><div className="shell"><div className="package-intro"><SectionTitle kicker="Curated packages" title={<>More care.<br/><em>Better value.</em></>} text="Built for quick resets, regular maintenance and the biggest days. Every package is easy to book and can be tailored during consultation."/><p className="package-note">All packages include a personal consultation, premium products and a finishing recommendation.</p></div><div className="package-grid">{packages.map((p,i)=><article key={p.name} className={`package-card reveal ${p.featured?"featured":""}`} style={{"--delay":`${i*90}ms`}}>{p.featured&&<span className="popular">Client favourite</span>}<div className="package-card-top"><span>{p.tag}</span><small>{p.duration}</small></div><h3>{p.name}</h3><div className="package-price"><b>{p.price}</b><span>{p.save}</span></div><ul>{p.includes.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a href={whatsappUrl(serviceMessage(`${p.name} package`))} target="_blank" rel="noreferrer" className={p.featured?"button-gold":"package-button"}>Choose package <ArrowUpRight size={16}/></a></article>)}</div></div></section>}
function Pricing(){return <section id="pricing" className="section pricing"><div className="shell price-layout"><SectionTitle kicker="Clear pricing" title={<>Invest in your<br/><em>best look.</em></>} text="Straightforward starting prices. Your barber will confirm the exact cost during consultation."/><div>{services.slice(0,8).map((s,i)=><div className="price-row" key={s.name}><span>{String(i+1).padStart(2,"0")}</span><h3>{s.name}</h3><i/><b>{s.price}</b></div>)}</div></div></section>}
const gallery=[{cat:"Hair",pos:"left",title:"Texture & shape"},{cat:"Beard",pos:"center",title:"The sharpest line"},{cat:"Skin",pos:"right",title:"Reset & restore"}];
function Gallery(){const[filter,setFilter]=useState("All"),[active,setActive]=useState(null);const items=filter==="All"?gallery:gallery.filter(x=>x.cat===filter);return <section id="gallery" className="section gallery"><div className="shell"><div className="gallery-head"><SectionTitle dark kicker="The work" title={<>Quiet confidence,<br/><em>well crafted.</em></>}/><div className="filters">{["All","Hair","Beard","Skin"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><div className="gallery-grid">{items.map(x=><button className="gallery-card" key={x.cat} onClick={()=>setActive(x)}><Image src="/images/grooming-editorial.png" alt={`${x.cat} grooming at The Hair Club`} fill sizes="(max-width:768px) 100vw,33vw" className={`cover ${x.pos}`}/><span><small>{x.cat}</small><b>{x.title}</b></span></button>)}</div>{active&&<div className="lightbox" role="dialog" aria-modal="true" onClick={()=>setActive(null)}><button aria-label="Close preview"><X size={32}/></button><div><Image src="/images/grooming-editorial.png" alt={`${active.cat} grooming preview`} fill className="contain" sizes="90vw"/></div></div>}</div></section>}
function Why(){const p=[["01","Expert hands","Skilled barbers and grooming specialists who understand shape, texture and personal style."],["02","Premium care","High-performance products selected for men’s hair, beard and skin."],["03","Easy booking","Choose your service and move directly to WhatsApp—no account or app required."]];return <section className="section why"><div className="shell"><SectionTitle kicker="Why The Hair Club" title={<>Details make the <em>difference.</em></>}/><div className="why-grid">{p.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}
function WhatsAppCTA(){return <section className="wa-cta"><div className="shell wa-cta-inner reveal"><div className="wa-cta-icon"><MessageCircle size={36}/><i/></div><div><p className="eyebrow">Fastest way to book</p><h2>Ready for your next look?</h2><p>Message us directly for available timings, service guidance and quick appointment confirmation.</p></div><a href={whatsappUrl(general())} target="_blank" rel="noreferrer" className="wa-cta-button"><span><b>Book on WhatsApp</b><small>+92 301 1700071</small></span><ArrowUpRight size={20}/></a></div></section>}
function Reviews(){return <section id="reviews" className="section reviews"><div className="shell"><SectionTitle kicker="Client notes" title={<>Trusted in the <em>chair.</em></>}/><div className="review-grid">{testimonials.map(t=><figure key={t.name}><div>{[0,1,2,3,4].map(i=><Star key={i} size={16} fill="currentColor"/>)}</div><blockquote>“{t.review}”</blockquote><figcaption><b>{t.name}</b><small>{t.role}</small></figcaption></figure>)}</div></div></section>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Booking(){const[form,setForm]=useState({name:"",phone:"",service:"",date:"",time:"",message:""}),[error,setError]=useState("");const update=e=>setForm({...form,[e.target.name]:e.target.value});function submit(e){e.preventDefault();if(!form.name||!form.phone||!form.service||!form.date||!form.time){setError("Please complete all required fields.");return}setError("");const msg=`Hello The Hair Club, I would like to book an appointment.\n\nName: ${form.name}\nPhone: ${form.phone}\nService: ${form.service}\nPreferred date: ${form.date}\nPreferred time: ${form.time}${form.message?`\nMessage: ${form.message}`:""}\n\nPlease confirm availability. Thank you.`;window.open(whatsappUrl(msg),"_blank","noopener,noreferrer")}return <section id="book" className="section booking"><div className="shell book-layout"><div><SectionTitle dark kicker="Reserve your chair" title={<>Your time.<br/><em>Your look.</em></>} text="Tell us what you need. We’ll open WhatsApp with your details ready to send."/><div className="hours">{salon.hours.map(x=><div key={x.days}><b>{x.days}</b><span>{x.time}</span></div>)}</div></div><form onSubmit={submit} noValidate><Field label="Full name *"><input name="name" value={form.name} onChange={update} autoComplete="name" placeholder="Your name"/></Field><Field label="Phone number *"><input name="phone" value={form.phone} onChange={update} autoComplete="tel" placeholder="03XX XXXXXXX"/></Field><Field label="Select service *"><select name="service" value={form.service} onChange={update}><option value="">Choose a service</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></Field><Field label="Preferred date *"><input type="date" name="date" min={new Date().toISOString().slice(0,10)} value={form.date} onChange={update}/></Field><Field label="Preferred time *"><input type="time" name="time" value={form.time} onChange={update}/></Field><Field label="Additional message"><input name="message" value={form.message} onChange={update} placeholder="Anything we should know?"/></Field>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button-gold form-submit wa-submit"><MessageCircle size={22}/><span><b>Continue on WhatsApp</b><small>Details will be ready to send</small></span></button><p className="form-note">No payment is taken here. Your appointment is confirmed when our team replies on WhatsApp.</p></form></div></section>}
function Contact(){return <section id="contact" className="section contact"><div className="shell split"><div><SectionTitle kicker="Visit us" title={<>Come in.<br/><em>Leave sharper.</em></>}/><div className="contact-list"><a href={`tel:${salon.phone.replace(/\s/g,"")}`}><Phone/><span><small>Call</small>{salon.phone}</span></a><a href={`mailto:${salon.email}`}><Mail/><span><small>Email</small>{salon.email}</span></a><a href={salon.mapUrl} target="_blank" rel="noreferrer"><MapPin/><span><small>Salon</small>{salon.address}</span></a></div><div className="contact-actions"><a className="button-dark" href={`tel:${salon.phone.replace(/\s/g,"")}`}>Call now</a><a className="button-outline" href={whatsappUrl(general())} target="_blank" rel="noreferrer">WhatsApp</a></div></div><a className="map-card" href={salon.mapUrl} target="_blank" rel="noreferrer"><div/><span><MapPin/></span><aside><small>Near Noor Autos</small><b>223 A Block, Ali Town</b><ArrowUpRight/></aside></a></div></section>}
function Footer(){return <footer><div className="shell"><div className="footer-main"><div><Brand light/><p>Contemporary men’s grooming, delivered with precision and understated hospitality.</p></div><div><h3>Quick links</h3><nav>{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav></div><div><h3>Follow</h3><div className="socials"><a href="#" aria-label="Instagram">IG</a><a href="#" aria-label="Facebook">FB</a><a href="#" aria-label="TikTok">TT</a></div></div></div><div className="copyright"><span>© {new Date().getFullYear()} {salon.name}. All rights reserved.</span><span>Placeholder details — ready for your brand.</span></div></div></footer>}
export default function SalonPage(){useEffect(()=>{const items=document.querySelectorAll(".reveal");const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -40px"});items.forEach(x=>io.observe(x));return()=>io.disconnect()},[]);return <><Navbar/><main><Hero/><About/><Services/><Packages/><Pricing/><Gallery/><Why/><WhatsAppCTA/><Reviews/><Booking/><Contact/></main><Footer/><a className="whatsapp-float" href={whatsappUrl(general())} target="_blank" rel="noreferrer" aria-label="Book on WhatsApp"><span className="wa-pulse"/><MessageCircle/><span className="wa-float-copy"><b>Book on WhatsApp</b><small>Quick response</small></span></a></>}
